services:
  postgresql:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracker_metrics
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
        context: .
        dockerfile: ./docker/Dockerfile
    environment:
      TRACKER_ORG_ID: "YOUR_ORG_ID"
      TRACKER_OAUTH_TOKEN: "YOUR_OAUTH_TOKEN"
      TRACKER_INITIAL_HISTORY_DEPTH: "7d"
    volumes:
      - ./config.docker.yaml:/app/config.yaml
      - ./migrations:/app/migrations
    depends_on:
      - postgresql